IF OBJECT_ID('Patients', 'U') IS NOT NULL AND COL_LENGTH('Patients', 'CNIC') IS NULL
    ALTER TABLE Patients ADD CNIC NVARCHAR(50) NULL;
GO
IF OBJECT_ID('Suppliers', 'U') IS NOT NULL AND COL_LENGTH('Suppliers', 'CNIC') IS NULL
    ALTER TABLE Suppliers ADD CNIC NVARCHAR(50) NULL;
GO
